version: '3.7'

services:
  webstore_node:
    image: node:16.13.0
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3666:3666
    depends_on:
      - webstore_database
      - localstack
    environment:
      DB_HOST: 'webstore_database'
      LOCALSTACK_HOST: 'localstack'
      LOCALSTACK_PORT: '4566'
    command: bash -c "yarn install && ./wait-for-it.sh -t 0 webstore_database:3306 -- yarn migrate && yarn seed && ./wait-for-it.sh -t 0 localstack:4566 -- yarn dev"
    networks:
      - webstore-network

  webstore_database:
    image: mysql:5.7.36
    container_name: webstore_database
    ports:
      - 3307:3306
    volumes:
      - ./.db_data:/var/lib/mysql
      # - ./db_scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: 'webstore'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - webstore-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
      - PERSISTENCE=1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - webstore-network

networks:
  webstore-network:
    driver: bridge
