import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AuthenticatedRoute from '@/components/AuthenticatedRoute';
import { userFromRequest } from '@/utils/auth';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>MAIN</h1>
      </div>
    </div>
  );
}

export default AuthenticatedRoute(Home);

export async function getServerSideProps(context) {
  const user = await userFromRequest(context.req);

  if (!user) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      user,
    },
  };
}
