import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AuthenticatedRoute from '@/components/AuthenticatedRoute';
import { userFromRequest } from '@/utils/auth';
import Layout from '@/components/Layout';
import { setUser } from '@/store/authSlice';

function Home({ user }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setUser(user));
  }, [dispatch, user]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="text-5xl font-bold">MAIN</h1>
      </div>
    </div>
  );
}

export default AuthenticatedRoute(Layout(Home));

export async function getServerSideProps(context) {
  const user = await userFromRequest(context.req);

  if (!user) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      user,
    },
  };
}
